"""goestools subprocess plumbing: config generation and binary discovery.

The GOES receive chain is `goesrecv` (SDR → demod → Viterbi → Reed-Solomon →
VCDUs) and `goesproc` (VCDUs → product files), both from
https://github.com/pietern/goestools. We generate the goesrecv config so its
nanomsg publisher endpoints always match what GoesService subscribes to, and
run goesproc with its working directory set to the product store so its
handler-relative output paths land where the API serves files from.
"""
from __future__ import annotations

import shutil
from importlib import resources
from pathlib import Path

from rt_hardware.config import GoesConfig

# Well-known locations `make install` / distro packages drop the goesproc
# handler config, in preference order. The GOES-R-specific file shipped with
# older releases comes first.
_GOESPROC_CONFIG_CANDIDATES = (
    "/usr/local/share/goestools/goesproc-goesr.conf",
    "/usr/share/goestools/goesproc-goesr.conf",
    "/usr/local/share/goestools/goesproc.conf",
    "/usr/share/goestools/goesproc.conf",
)


def render_goesrecv_config(cfg: GoesConfig) -> str:
    """goesrecv.conf with publishers bound to the ports GoesService consumes."""
    sdr_section = f"""\
[{cfg.sdr}]
frequency = {int(cfg.downlink_freq_hz)}
sample_rate = {int(cfg.sample_rate_hz)}
gain = {int(cfg.gain_db)}
bias_tee = {"true" if cfg.lna_bias_tee_enabled else "false"}
"""
    return f"""\
# Generated by rt-hardware from config.toml [goes] — do not edit; changes
# belong in config.toml. Regenerated on every pipeline (re)spawn.

[demodulator]
mode = "{cfg.mode}"
source = "{cfg.sdr}"

{sdr_section}
[costas]
max_deviation = 200e3

[clock_recovery.sample_publisher]
bind = "tcp://127.0.0.1:{cfg.symbol_port}"
send_buffer = 2097152

[decoder.packet_publisher]
bind = "tcp://127.0.0.1:{cfg.packet_port}"
send_buffer = 1048576

[demodulator.stats_publisher]
bind = "tcp://127.0.0.1:{cfg.demod_stats_port}"
send_buffer = 2097152

[decoder.stats_publisher]
bind = "tcp://127.0.0.1:{cfg.decoder_stats_port}"
send_buffer = 2097152
"""


def write_goesrecv_config(cfg: GoesConfig, state_dir: Path) -> Path:
    path = state_dir / "goesrecv-generated.conf"
    state_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(render_goesrecv_config(cfg))
    return path


def resolve_goesproc_config(cfg: GoesConfig, state_dir: Path) -> Path:
    """Pick the goesproc handler config: explicit > installed > shipped fallback."""
    if cfg.goesproc_config:
        return Path(cfg.goesproc_config)
    for candidate in _GOESPROC_CONFIG_CANDIDATES:
        if Path(candidate).exists():
            return Path(candidate)
    # Fall back to the minimal handler set shipped with this package,
    # materialised into the state dir so goesproc gets a real file path.
    fallback = state_dir / "goesproc-fallback.conf"
    state_dir.mkdir(parents=True, exist_ok=True)
    fallback.write_text(
        resources.files("rt_hardware.goes").joinpath("goesproc-fallback.conf").read_text(),
    )
    return fallback


def goesrecv_command(cfg: GoesConfig, config_path: Path) -> list[str]:
    return [cfg.goesrecv_bin, "-c", str(config_path)]


def goesproc_command(cfg: GoesConfig, handler_config: Path) -> list[str]:
    return [
        cfg.goesproc_bin,
        "-c", str(handler_config),
        "-m", "packet",
        "--subscribe", f"tcp://127.0.0.1:{cfg.packet_port}",
    ]


def missing_binaries(cfg: GoesConfig) -> list[str]:
    """Which goestools binaries can't be found (empty list = ready to run)."""
    return [b for b in (cfg.goesrecv_bin, cfg.goesproc_bin) if shutil.which(b) is None]


__all__ = (
    "render_goesrecv_config",
    "write_goesrecv_config",
    "resolve_goesproc_config",
    "goesrecv_command",
    "goesproc_command",
    "missing_binaries",
)
