// Queue types re-exported from the generated `./types` so existing call sites
// keep working. Both shapes are generated by `python -m
// radiotelescope.scripts.dump_types` — run `npm run sync-types` to regenerate.
//
// Network helpers for the queue live alongside the rest of the REST surface
// in `./api.ts` — see `api.queueConfig`, `api.queueStatus`, `api.joinQueue`,
// `api.leaveQueue`.

export type { QueueConfigResponse as QueueConfig, QueueStatus } from './types';
